[package]
name = "github-token-app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.29.0", features = ["full"] }
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"